# Generated by Django 4.1.3 on 2022-11-09 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_car_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='engine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(choices=[(2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005'), (2004, '2004'), (2003, '2003'), (2002, '2002'), (2001, '2001'), (2000, '2000'), (1999, '1999'), (1998, '1998'), (1997, '1997'), (1996, '1996'), (1995, '1995'), (1994, '1994'), (1993, '1993'), (1992, '1992'), (1991, '1991'), (1990, '1990'), (1989, '1989'), (1988, '1988'), (1987, '1987'), (1986, '1986'), (1985, '1985'), (1984, '1984'), (1983, '1983'), (1982, '1982'), (1981, '1981'), (1980, '1980'), (1979, '1979'), (1978, '1978'), (1977, '1977'), (1976, '1976'), (1975, '1975'), (1974, '1974'), (1973, '1973'), (1972, '1972'), (1971, '1971'), (1970, '1970'), (1969, '1969'), (1968, '1968'), (1967, '1967'), (1966, '1966'), (1965, '1965'), (1964, '1964'), (1963, '1963'), (1962, '1962'), (1961, '1961'), (1960, '1960'), (1959, '1959'), (1958, '1958'), (1957, '1957'), (1956, '1956'), (1955, '1955'), (1954, '1954'), (1953, '1953'), (1952, '1952'), (1951, '1951'), (1950, '1950'), (1949, '1949'), (1948, '1948'), (1947, '1947'), (1946, '1946'), (1945, '1945'), (1944, '1944'), (1943, '1943'), (1942, '1942'), (1941, '1941'), (1940, '1940'), (1939, '1939'), (1938, '1938'), (1937, '1937'), (1936, '1936'), (1935, '1935'), (1934, '1934'), (1933, '1933'), (1932, '1932'), (1931, '1931'), (1930, '1930'), (1929, '1929'), (1928, '1928'), (1927, '1927'), (1926, '1926'), (1925, '1925'), (1924, '1924'), (1923, '1923'), (1922, '1922'), (1921, '1921'), (1920, '1920'), (1919, '1919'), (1918, '1918'), (1917, '1917'), (1916, '1916'), (1915, '1915'), (1914, '1914'), (1913, '1913'), (1912, '1912'), (1911, '1911'), (1910, '1910'), (1909, '1909'), (1908, '1908'), (1907, '1907'), (1906, '1906'), (1905, '1905'), (1904, '1904'), (1903, '1903'), (1902, '1902'), (1901, '1901'), (1900, '1900'), (1899, '1899')], default=2022, verbose_name='year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autoservice.carmodel', verbose_name='car model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.CharField(max_length=200, verbose_name='client name'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate_number',
            field=models.CharField(max_length=10, verbose_name='license plate number'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(max_length=50, verbose_name='make'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=50, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autoservice.car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservice.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservice.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
