# Generated by Django 4.1.3 on 2022-11-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_carmodel_engine_carmodel_year_alter_car_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='photo'),
        ),
    ]
