# Generated by Django 4.1.3 on 2022-11-16 13:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0007_alter_carmodel_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(default='-', max_length=1000, verbose_name='description'),
        ),
    ]
