# Generated by Django 4.1.3 on 2022-11-16 13:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
    ]
