# Generated by Django 4.1.3 on 2022-11-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0010_orderreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='summary',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'new'), ('a', 'advance payment taken'), ('o', 'ordered parts'), ('w', 'working'), ('d', 'done'), ('c', 'cancelled'), ('p', 'paid')], default='n', max_length=1, verbose_name='status'),
        ),
    ]
