# Generated by Django 4.1.3 on 2022-11-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0011_remove_carmodel_summary_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
